imports:
  - { resource: common/adapter.yml }
  - { resource: common/buffer.yml }
  - { resource: common/config.yml }
  - { resource: common/context.yml }
  - { resource: common/factory.yml }
  - { resource: common/handler.yml }
  - { resource: common/provider.yml }
  - { resource: common/repository.yml }
  - { resource: common/segment.yml }

services:
  psxmarketingwithgoogle:
    class: 'PsxMarketingWithGoogle'
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'psxmarketingwithgoogle'
