<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXdas5if\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXdas5if/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXdas5if.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXdas5if\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXdas5if\appProdProjectContainer([
    'container.build_hash' => 'Xdas5if',
    'container.build_id' => '82f3dffc',
    'container.build_time' => 1649573015,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXdas5if');
