services:
  PrestaShop\Module\PsxMarketingWithGoogle\Factory\ApiClientFactory:
    class: PrestaShop\Module\PsxMarketingWithGoogle\Factory\ApiClientFactory
    arguments:
      - '@PrestaShop\Module\PsxMarketingWithGoogle\Config\Env'
