services:
  PrestaShop\Module\PsxMarketingWithGoogle\Builder\CarrierBuilder:
    class: PrestaShop\Module\PsxMarketingWithGoogle\Builder\CarrierBuilder
    arguments:
     - '@PrestaShop\Module\PsxMarketingWithGoogle\Repository\CarrierRepository'
     - '@PrestaShop\Module\PsxMarketingWithGoogle\Repository\CountryRepository'
     - '@PrestaShop\Module\PsxMarketingWithGoogle\Repository\StateRepository'
     - '@PrestaShop\Module\PsxMarketingWithGoogle\Repository\TaxRepository'
     - '@PrestaShop\Module\PsxMarketingWithGoogle\Adapter\ConfigurationAdapter'

