<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\Module\PsxMarketingWithGoogle\Factory\ApiClientFactory' shared service.

return $this->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\Factory\\ApiClientFactory'] = new \PrestaShop\Module\PsxMarketingWithGoogle\Factory\ApiClientFactory(${($_ = isset($this->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\Config\\Env']) ? $this->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\Config\\Env'] : ($this->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\Config\\Env'] = new \PrestaShop\Module\PsxMarketingWithGoogle\Config\Env())) && false ?: '_'});
