<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'psxmarketingwithgoogle.db' shared service.

return $this->services['psxmarketingwithgoogle.db'] = \Db::getInstance();
