<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\Module\PsxMarketingWithGoogle\Repository\ShopRepository' shared service.

return $this->services['PrestaShop\\Module\\PsxMarketingWithGoogle\\Repository\\ShopRepository'] = new \PrestaShop\Module\PsxMarketingWithGoogle\Repository\ShopRepository();
